#!/bin/bash

. /opt/conda/etc/profile.d/conda.sh

conda info --envs | grep 'condaR_TCL' &> /dev/null

if [[ $? -eq 1 ]]; then
    conda create -c conda-forge -y -n condaR_TCL R=4.2 tk pip cmake
    conda activate condaR_TCL
    pip install h5py
    pip install tensorflow
    echo "install.packages(\"keras\", repos=\"https://cran.rstudio.com\")" | R --no-save
    echo "install.packages(\"caret\", repos=\"https://cran.rstudio.com\")" | R --no-save
    echo "install.packages(\"e1071\", repos=\"https://cran.rstudio.com\")" | R --no-save
    echo "install.packages(\"FactoMineR\", repos=\"https://cran.rstudio.com\")" | R --no-save
fi
