#!/bin/bash

. /opt/conda/etc/profile.d/conda.sh

conda info --envs | grep 'condaR_TCL' &> /dev/null

if [[ $? -eq 1 ]]; then
    conda create -y -n condaR_TCL R=3.6 tk
    conda activate condaR_TCL
    pip install h5py
    pip install tensorflow==2.0.0
    echo "install.packages(\"keras\", repos=\"https://cran.rstudio.com\")" | R --no-save
    echo "install.packages(\"caret\", repos=\"https://cran.rstudio.com\")" | R --no-save
    echo "install.packages(\"e1071\", repos=\"https://cran.rstudio.com\")" | R --no-save
    echo "install.packages(\"FactoMineR\", repos=\"https://cran.rstudio.com\")" | R --no-save
fi
