# Generated by Django 2.0.13 on 2019-06-05 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20190529_1245'),
        ('assays', '0004_auto_20190605_1558'),
        ('studies', '0002_auto_20190529_1245'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ontologies', '0005_auto_20190529_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tsx_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='user')),
                ('status', models.CharField(choices=[('PRIVATE', 'Private'), ('PENDING', 'Pending'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=20)),
                ('signature_type', models.CharField(choices=[('GENOMICS', 'Genomics'), ('METABOLOMICS', 'Metabolomics')], default='GENOMICS', max_length=20)),
                ('phenotype_description', models.TextField(verbose_name='Phenotype description')),
                ('experimental_design', models.TextField(verbose_name='Experimental design')),
                ('dev_stage', models.CharField(choices=[('FETAL', 'Fetal'), ('EMBRYONIC', 'Embryonic'), ('LARVA', 'Larva'), ('NEONATAL', 'Neo-natal'), ('JUVENILE', 'Juvenile'), ('PREPUBERTAL', 'Prepubertal'), ('ADULTHOOD', 'Adulthood'), ('ELDERLY', 'Elderly'), ('NA', 'Na'), ('OTHER', 'Other')], default='NA', max_length=50)),
                ('generation', models.CharField(choices=[('F0', 'F0'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5')], default='F0', max_length=10)),
                ('sex_type', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('BOTH', 'Both'), ('NA', 'Na'), ('OTHER', 'Other')], default='MALE', max_length=10)),
                ('exp_type', models.CharField(choices=[('EXVIVO', 'Ex-vivo'), ('INVITRO', 'In-vitro'), ('INVIVO', 'In-vivo'), ('NA', 'Na'), ('OTHER', 'Other')], default='NA', max_length=10)),
                ('chemical_slug', models.CharField(max_length=200)),
                ('technology_slug', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('control_sample_number', models.FloatField(blank=True, default=None, null=True)),
                ('treated_sample_number', models.FloatField(blank=True, default=None, null=True)),
                ('pvalue', models.FloatField(blank=True, default=None, null=True)),
                ('cutoff', models.FloatField(blank=True, default=None, null=True)),
                ('statistical_processing', models.TextField(verbose_name='Statistical processing')),
                ('up_gene_file_path', models.CharField(max_length=500)),
                ('down_gene_file_path', models.CharField(max_length=500)),
                ('interrogated_gene_file_path', models.CharField(max_length=500)),
                ('additional_file_path', models.CharField(max_length=500)),
                ('gene_id', models.CharField(choices=[('ENTREZ', 'Entrez genes'), ('ENSEMBL', 'Ensembl')], default='ENTREZ', max_length=50)),
                ('ass_subClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_of_of', to='assays.Assay')),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_used_in', to='ontologies.Cell')),
                ('cell_ligne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_used_in', to='ontologies.CellLine')),
                ('chemical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_used_in', to='ontologies.Chemical')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures_signature_created_by', to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_used_in', to='ontologies.Disease')),
                ('ftc_subClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_of_of', to='assays.Factor')),
                ('organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_used_in', to='ontologies.Species')),
                ('prj_subClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_of_of', to='projects.Project')),
                ('std_subClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_of_of', to='studies.Study')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_used_in', to='ontologies.Experiment')),
                ('tissue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_used_in', to='ontologies.Tissue')),
            ],
        ),
    ]
