# Generated by Django 2.0.13 on 2019-07-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='cell_ligne',
            new_name='cell_line',
        ),
        migrations.RenameField(
            model_name='signature',
            old_name='ftc_subClass',
            new_name='factor',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='ass_subClass',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='prj_subClass',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='std_subClass',
        ),
    ]
