# Generated by Django 2.0.13 on 2019-08-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('signatures', '0004_auto_20190723_0815'), ('signatures', '0005_auto_20190801_0815')]

    dependencies = [
        ('signatures', '0003_remove_signature_status'),
        ('ontologies', '0006_auto_20190702_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='disease',
        ),
        migrations.AddField(
            model_name='signature',
            name='disease',
            field=models.ManyToManyField(blank=True, related_name='signature_used_in', to='ontologies.Disease'),
        ),
        migrations.RemoveField(
            model_name='signature',
            name='cell',
        ),
        migrations.AddField(
            model_name='signature',
            name='cell',
            field=models.ManyToManyField(blank=True, related_name='signature_used_in', to='ontologies.Cell'),
        ),
        migrations.RemoveField(
            model_name='signature',
            name='cell_line',
        ),
        migrations.AddField(
            model_name='signature',
            name='cell_line',
            field=models.ManyToManyField(blank=True, related_name='signature_used_in', to='ontologies.CellLine'),
        ),
        migrations.RemoveField(
            model_name='signature',
            name='chemical',
        ),
        migrations.AddField(
            model_name='signature',
            name='chemical',
            field=models.ManyToManyField(blank=True, related_name='signature_used_in', to='ontologies.Chemical'),
        ),
        migrations.RemoveField(
            model_name='signature',
            name='organism',
        ),
        migrations.AddField(
            model_name='signature',
            name='organism',
            field=models.ManyToManyField(blank=True, related_name='signature_used_in', to='ontologies.Species'),
        ),
        migrations.RemoveField(
            model_name='signature',
            name='technology',
        ),
        migrations.AddField(
            model_name='signature',
            name='technology',
            field=models.ManyToManyField(blank=True, related_name='signature_used_in', to='ontologies.Experiment'),
        ),
        migrations.RemoveField(
            model_name='signature',
            name='tissue',
        ),
        migrations.AddField(
            model_name='signature',
            name='tissue',
            field=models.ManyToManyField(blank=True, related_name='signature_used_in', to='ontologies.Tissue'),
        ),
    ]
