# Generated by Django 2.0.13 on 2019-10-08 11:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0004_auto_20190723_0815_squashed_0005_auto_20190801_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='expression_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='additional_file_path',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='down_gene_file_path',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='interrogated_gene_file_path',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='up_gene_file_path',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
