# Generated by Django 2.0.13 on 2019-10-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0006_signature_expression_values_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='chemical_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='experimental_design',
            field=models.TextField(blank=True, null=True, verbose_name='Experimental design'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='phenotype_description',
            field=models.TextField(blank=True, null=True, verbose_name='Phenotype description'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='platform',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='statistical_processing',
            field=models.TextField(blank=True, null=True, verbose_name='Statistical processing'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='technology_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
