# Generated by Django 2.0.13 on 2019-11-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0007_auto_20191030_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='down_gene_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='interrogated_gene_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='up_gene_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
