# Generated by Django 2.0.13 on 2019-11-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0008_auto_20191104_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='control_sample_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='generation',
            field=models.CharField(choices=[('NA', 'NA'), ('F0', 'F0'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5')], default='F0', max_length=10),
        ),
        migrations.AlterField(
            model_name='signature',
            name='treated_sample_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
