# Generated by Django 2.0.13 on 2020-04-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0010_signature_cell_line_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signature_type',
            field=models.CharField(choices=[('GENOMICS', 'Genomics'), ('METABOLOMICS', 'Metabolomics'), ('TRANSCRIPTOMICS', 'Transcriptomics'), ('EPIGENOMICS', 'Epigenomics'), ('PROTEOMICS', 'Proteomics')], default='GENOMICS', max_length=20),
        ),
    ]
