# Generated by Django 2.0.13 on 2021-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0011_auto_20200403_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='chemical_slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
