# Generated by Django 2.0.13 on 2019-05-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologies', '0003_auto_20190529_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biological',
            name='as_ancestor',
            field=models.ManyToManyField(blank=True, related_name='_biological_as_ancestor_+', to='ontologies.Biological'),
        ),
        migrations.AlterField(
            model_name='biological',
            name='as_parent',
            field=models.ManyToManyField(blank=True, related_name='_biological_as_parent_+', to='ontologies.Biological'),
        ),
    ]
