# Generated by Django 2.0.13 on 2019-05-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologies', '0004_auto_20190529_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='biological',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='cell',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='cellline',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='disease',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='species',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='tissue',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
    ]
