# Generated by Django 2.0.13 on 2019-12-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superproject',
            name='contact_mail',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
