# Generated by Django 2.0.13 on 2020-03-05 15:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import functools
import toxsign.clusters.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.CharField(max_length=5)),
                ('distance_method', models.CharField(choices=[('euclidean', 'Euclidean'), ('correlation', 'Correlation')], max_length=20)),
                ('conditions_file', models.FileField(upload_to=functools.partial(toxsign.clusters.models.get_upload_path, *('cluster.txt',), **{}))),
                ('signature_file', models.FileField(upload_to=functools.partial(toxsign.clusters.models.get_upload_path, *('signature.txt',), **{}))),
                ('chemical_enrichment_file', models.FileField(upload_to=functools.partial(toxsign.clusters.models.get_upload_path, *('chem2enr.csv',), **{}))),
                ('gene_enrichment_file', models.FileField(upload_to=functools.partial(toxsign.clusters.models.get_upload_path, *('gene2enr.csv',), **{}))),
                ('signature', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('conditions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
