# Generated by Django 2.0.13 on 2020-03-05 15:55

from django.db import migrations, models
import functools
import toxsign.clusters.models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='chemical_enrichment_file',
            field=models.FileField(blank=True, upload_to=functools.partial(toxsign.clusters.models.get_upload_path, *('chem2enr.csv',), **{})),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='gene_enrichment_file',
            field=models.FileField(blank=True, upload_to=functools.partial(toxsign.clusters.models.get_upload_path, *('gene2enr.csv',), **{})),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='signature_file',
            field=models.FileField(blank=True, upload_to=functools.partial(toxsign.clusters.models.get_upload_path, *('signature.txt',), **{})),
        ),
    ]
