# Generated by Django 2.0.13 on 2019-05-23 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prj_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='user')),
                ('status', models.CharField(choices=[('PRIVATE', 'Private'), ('PENDING', 'Pending'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=20)),
                ('description', models.TextField(verbose_name='description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_project_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
