# Generated by Django 2.0.13 on 2019-05-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='prj_id',
            new_name='tsx_id',
        ),
    ]
