# Generated by Django 2.0.13 on 2019-07-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190717_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_project', 'View project'),)},
        ),
    ]
