# Generated by Django 2.0.13 on 2019-09-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superprojects', '__first__'),
        ('projects', '0005_auto_20190717_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='superproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_of', to='superprojects.Superproject'),
        ),
    ]
