# Generated by Django 2.0.13 on 2019-09-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_superproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='experimental_design',
            field=models.TextField(blank=True, verbose_name='Experimental design'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('INTERVENTIONAL', 'Interventional'), ('OBSERVATIONAL', 'Observational')], default='INTERVENTIONAL', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True, verbose_name='Results'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
