# Generated by Django 2.0.13 on 2019-10-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190905_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cross_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pubmed_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
