# Generated by Django 2.0.13 on 2019-11-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20191030_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='experimental_design',
        ),
        migrations.RemoveField(
            model_name='project',
            name='results',
        ),
    ]
