# Generated by Django 2.0.13 on 2019-11-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('projects', '0010_auto_20191112_0949'), ('projects', '0011_auto_20191112_0951')]

    dependencies = [
        ('projects', '0009_auto_20191106_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cross_link',
            field=models.TextField(blank=True, null=True, verbose_name='cross_link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
