# Generated by Django 2.0.13 on 2021-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20191112_0949_squashed_0011_auto_20191112_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
