# Generated by Django 2.0.13 on 2019-05-29 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35)),
                ('slug', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('html_name', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='user')),
                ('status', models.CharField(choices=[('STABLE', 'Stable'), ('DEVELOPPMENT', 'Developpment'), ('OUTDATED', 'Outdated')], default='DEVELOPPMENT', max_length=20)),
                ('command_line', models.CharField(max_length=250, null=True)),
                ('path', models.CharField(max_length=250, null=True)),
                ('script_name', models.CharField(max_length=250, null=True)),
                ('visuel', models.ImageField(null=True, upload_to='tools/', verbose_name='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools_tool_created_by', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='tool_tag_description', to='tools.Tag')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools_tool_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
