# Generated by Django 2.0.13 on 2019-08-07 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('parameter', models.CharField(blank=True, max_length=10, null=True)),
                ('multiple', models.BooleanField(default=False)),
                ('user_filled', models.BooleanField(default=True)),
                ('optional', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ArgumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='TEXT', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='form_name',
            field=models.CharField(default='default_form', max_length=100),
        ),
        migrations.AddField(
            model_name='argument',
            name='argument_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.ArgumentType'),
        ),
        migrations.AddField(
            model_name='argument',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='tools.Tool'),
        ),
        migrations.AddField(
            model_name='tool',
            name='argument_types',
            field=models.ManyToManyField(through='tools.Argument', to='tools.ArgumentType'),
        ),
    ]
