# Generated by Django 2.0.13 on 2019-10-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20190812_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='command_line',
            new_name='script_file',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='path',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='script_name',
        ),
    ]
