# Generated by Django 2.0.13 on 2019-10-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20191010_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='custom_result_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
