# Generated by Django 2.0.13 on 2020-03-11 15:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_predictionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
