# Generated by Django 2.0.13 on 2019-05-28 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('ontologies', '0001_initial'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('as_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='user')),
                ('status', models.CharField(choices=[('PRIVATE', 'Private'), ('PENDING', 'Pending'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=20)),
                ('additional_info', models.TextField(verbose_name='Additional information')),
                ('experimental_design', models.TextField(verbose_name='Experimental design')),
                ('dev_stage', models.CharField(choices=[('FETAL', 'Fetal'), ('EMBRYONIC', 'Embryonic'), ('LARVA', 'Larva'), ('NEONATAL', 'Neo-natal'), ('JUVENILE', 'Juvenile'), ('PREPUBERTAL', 'Prepubertal'), ('ADULTHOOD', 'Adulthood'), ('ELDERLY', 'Elderly'), ('NA', 'Na'), ('OTHER', 'Other')], default='NA', max_length=50)),
                ('generation', models.CharField(choices=[('F0', 'F0'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5')], default='F0', max_length=10)),
                ('sex_type', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('BOTH', 'Both'), ('NA', 'Na'), ('OTHER', 'Other')], default='MALE', max_length=10)),
                ('exp_type', models.CharField(choices=[('EXVIVO', 'Ex-vivo'), ('INVITRO', 'In-vitro'), ('INVIVO', 'In-vivo'), ('NA', 'Na'), ('OTHER', 'Other')], default='NA', max_length=10)),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assay_used_in', to='ontologies.Cell')),
                ('cell_ligne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assay_used_in', to='ontologies.CellLine')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assays_assay_created_by', to=settings.AUTH_USER_MODEL)),
                ('organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assay_used_in', to='ontologies.Species')),
                ('prj_subClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assay_of', to='projects.Project')),
                ('std_subClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assay_of', to='studies.Study')),
                ('tissue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assay_used_in', to='ontologies.Tissue')),
            ],
        ),
    ]
