# Generated by Django 2.0.13 on 2019-06-05 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ontologies', '0005_auto_20190529_1039'),
        ('assays', '0002_auto_20190529_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tsx_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='user')),
                ('chemical_slug', models.CharField(max_length=200)),
                ('factor_type', models.CharField(choices=[('CHEMICAL', 'Chemical'), ('BIOLOGICAL', 'Biological'), ('PHYSICAL', 'Physical')], default='CHEMICAL', max_length=50)),
                ('route', models.CharField(max_length=200)),
                ('vehicule', models.CharField(max_length=200)),
                ('dose_value', models.FloatField(blank=True, default=None, null=True)),
                ('dose_unit', models.CharField(choices=[('M', 'M'), ('mM', 'mM'), ('µM', 'µM'), ('g/mL', 'g/mL'), ('mg/mL', 'mg/mL'), ('µg/mL', 'µg/mL'), ('ng/mL', 'ng/mL'), ('mg/kg', 'mg/kg'), ('µg/kg', 'µg/kg'), ('µg/kg', 'µg/kg'), ('ng/kg', 'ng/kg'), ('ng/g lipid', 'ng/g lipid'), ('ng/g creatinine', 'ng/g creatinine')], default='M', max_length=50)),
                ('exposure_time', models.FloatField(blank=True, default=None, null=True)),
                ('exposure_frequencie', models.CharField(max_length=200)),
                ('additional_info', models.TextField(verbose_name='Additional information')),
                ('chemical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assay_used_in', to='ontologies.Chemical')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assays_factor_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
