# Generated by Django 2.0.13 on 2019-06-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20190529_1245'),
        ('projects', '0002_auto_20190529_1245'),
        ('assays', '0003_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='ass_subClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factor_of', to='assays.Assay'),
        ),
        migrations.AddField(
            model_name='factor',
            name='prj_subClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factor_of', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='factor',
            name='std_subClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factor_of', to='studies.Study'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='chemical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factor_used_in', to='ontologies.Chemical'),
        ),
    ]
