# Generated by Django 2.0.13 on 2019-07-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0004_auto_20190605_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assay',
            old_name='cell_ligne',
            new_name='cell_line',
        ),
        migrations.RenameField(
            model_name='assay',
            old_name='std_subClass',
            new_name='study',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='ass_subClass',
            new_name='assay',
        ),
        migrations.RemoveField(
            model_name='assay',
            name='prj_subClass',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='prj_subClass',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='std_subClass',
        ),
    ]
