# Generated by Django 2.0.13 on 2019-09-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_superproject'),
        ('assays', '0006_remove_assay_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assay',
            name='study',
        ),
        migrations.AddField(
            model_name='assay',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assay_of', to='projects.Project'),
        ),
    ]
