# Generated by Django 2.0.13 on 2019-09-09 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('assays', '0007_auto_20190909_0804'), ('assays', '0008_auto_20190909_0811')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assays', '0006_remove_assay_status'),
        ('ontologies', '0006_auto_20190702_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalsubFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_slug', models.CharField(blank=True, max_length=200)),
                ('route', models.CharField(blank=True, max_length=200)),
                ('vehicule', models.CharField(blank=True, max_length=200)),
                ('dose_value', models.FloatField(blank=True, default=None, null=True)),
                ('dose_unit', models.CharField(choices=[('M', 'M'), ('mM', 'mM'), ('µM', 'µM'), ('g/mL', 'g/mL'), ('mg/mL', 'mg/mL'), ('µg/mL', 'µg/mL'), ('ng/mL', 'ng/mL'), ('mg/kg', 'mg/kg'), ('µg/kg', 'µg/kg'), ('µg/kg', 'µg/kg'), ('ng/kg', 'ng/kg'), ('ng/g lipid', 'ng/g lipid'), ('ng/g creatinine', 'ng/g creatinine')], default='M', max_length=50)),
                ('exposure_time', models.FloatField(blank=True, default=None, null=True)),
                ('exposure_frequencie', models.CharField(blank=True, max_length=200)),
                ('additional_info', models.TextField(verbose_name='Additional information')),
                ('chemical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_subfactor_used_in', to='ontologies.Chemical')),
            ],
        ),
        migrations.RemoveField(
            model_name='factor',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='chemical',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='chemical_slug',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='dose_unit',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='dose_value',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='exposure_frequencie',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='exposure_time',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='factor_type',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='route',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='vehicule',
        ),
        migrations.AddField(
            model_name='chemicalsubfactor',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_subfactor_of', to='assays.Factor'),
        ),
        migrations.AddField(
            model_name='chemicalsubfactor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicalsubfactor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assays_chemicalsubfactor_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chemicalsubfactor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='user'),
        ),
    ]
