# Generated by Django 2.0.13 on 2019-11-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0007_create_chemical_subfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='assay',
            name='results',
            field=models.TextField(blank=True, verbose_name='Results'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='experimental_design',
            field=models.TextField(blank=True, verbose_name='Experimental design'),
        ),
    ]
