# Generated by Django 2.0.13 on 2019-11-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0008_auto_20191106_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='generation',
            field=models.CharField(choices=[('NA', 'Na'), ('F0', 'F0'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5')], default='F0', max_length=10),
        ),
        migrations.AlterField(
            model_name='chemicalsubfactor',
            name='dose_unit',
            field=models.CharField(choices=[('NA', 'NA'), ('IC', 'IC'), ('EC', 'EC'), ('M', 'M'), ('mM', 'mM'), ('µM', 'µM'), ('nM', 'nM'), ('pM', 'pM'), ('fM', 'fM'), ('g/mL', 'g/mL'), ('mg/mL', 'mg/mL'), ('µg/mL', 'µg/mL'), ('ng/mL', 'ng/mL'), ('mg/kg', 'mg/kg'), ('µg/kg', 'µg/kg'), ('ng/kg', 'ng/kg'), ('ng/g lipid', 'ng/g lipid'), ('ng/g creatinine', 'ng/g creatinine')], default='M', max_length=50),
        ),
    ]
