# Generated by Django 2.0.13 on 2019-11-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0009_auto_20191108_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='cell_line_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
