# Generated by Django 2.0.13 on 2021-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0010_assay_cell_line_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='chemicalsubfactor',
            name='chemical_slug',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
