# Generated by Django 2.0.13 on 2021-11-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0011_auto_20211104_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalsubfactor',
            name='CAS',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='chemicalsubfactor',
            name='pubchemid',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
