# Generated by Django 2.0.13 on 2021-12-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0012_auto_20211105_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
