# Generated by Django 2.0.13 on 2019-05-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institut',
            field=models.CharField(blank=True, max_length=255, verbose_name='User institut'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last name of User'),
        ),
    ]
