# Generated by Django 2.0.13 on 2019-08-13 08:52

import os

from django.core.management.base import BaseCommand, CommandError

from toxsign.superprojects.models import Superproject
from toxsign.projects.models import Project
from toxsign.users.models import User


def classify_data():

    admin_user = User.objects.filter(is_superuser=True)
    if not admin_user:
        print("No superuser created, aborting")
    else:
        admin_user = admin_user[0]

    drugmatrix = _get_drugmatrix(admin_user)
    tg_gates = _get_tg_gates(admin_user)

    for project in Project.objects.all():

        if project.name.startswith("Open TG-GATEs") and not project.superproject == tg_gates:
            project.superproject = tg_gates
            project.save()
            print("Classified project " + project.tsx_id + " in Open TG-GATEs superproject")

        elif project.name.startswith("DrugMatrix") and not project.superproject == drugmatrix:
            project.superproject = drugmatrix
            project.save()
            print("Classified project " + project.tsx_id + " in DrugMatrix superproject")

def _get_drugmatrix(admin_user):
    sprojects = Superproject.objects.filter(name="DrugMatrix")
    if sprojects:
        return sprojects[0]
    else:
        name = "DrugMatrix"
        description = "<a target='_blank' href='https://ntp.niehs.nih.gov/data/drugmatrix/'>DrugMatrix</a>, produced by the <a target='_blank' href='https://ntp.niehs.nih.gov/'>U.S. National Toxicology Program</a>, is a molecular toxicology reference database and informatics system. DrugMatrix is populated with the comprehensive results of thousands of highly controlled and standardized toxicological experiments in which rats or primary rat hepatocytes were systematically treated with therapeutic, industrial, and environmental chemicals at both non-toxic and toxic doses."
        description += "<br>" + "The DrugMatrix database is one of the world’s largest toxicogenomic reference resources. The ToxFX reporting system, a companion to DrugMatrix, allows users to quickly create fully annotated reports from DrugMatrix data. Together, these tools increase the efficiency of the toxicological assessment process and reduce the amount of time needed to formulate a xenobiotic’s potential for toxicity."
        description += "<br>" + "The heart of the DrugMatrix database is large-scale gene expression data. The primary value that DrugMatrix provides to the toxicology community is in its capacity to use toxicogenomic data to perform rapid toxicological evaluations."
        description += "<br>" + "The resource is no longer hosted for external use, but the data is <a href='https://ntp.niehs.nih.gov/data/drugmatrix/' target='_blank' >available</a> in a number of formats."

        drugmatrix = Superproject(name=name, description=description, created_by=admin_user)
        drugmatrix.save()
        return drugmatrix


def _get_tg_gates(admin_user):

    sprojects = Superproject.objects.filter(name="Open TG-GATEs")
    if sprojects:
        return sprojects[0]
    else:
        name = "Open TG-GATEs"
        description = "Open TG-GATEs is a toxicogenomics database open to the public for researchers to utilize research results of TGP and TGP2, and releases the data of 170 compounds stored in TG-GATEs. In Open TG-GATEs, it is possible to search toxicogenomics data by compound name or pathological finding. It is also possible to download gene expression data associated with phenotype data such as pathological findings as a CEL file."
        tg_gates = Superproject(name=name, description=description, created_by=admin_user)
        tg_gates.save()
        return tg_gates


class Command(BaseCommand):

    help = 'Classify projects in DrugMatrix and Open TG-GATEs'

    def handle(self, *args, **options):
        classify_data()
