# Generated by Django 2.0.13 on 2019-08-13 08:52
from django.core.management.base import BaseCommand, CommandError
from django_elasticsearch_dsl.registries import registry
from load_ontologies import launch_import
from load_genes import populate_genes
from load_pathways import process_pathways
from load_tools import populate_default_tools
from load_data import launch_data

class Command(BaseCommand):

    help = 'Populate all'

    def add_arguments(self, parser):
        # Positional arguments
        parser.add_argument('bson_folder', type=str, help='Folder containing the bson files')
        parser.add_argument('signature_data_folder', type=str, help='Folder containing the signature data (TSPX, etc...)')
        parser.add_argument('admin_mail', type=str, help='Admin mail adress')
        parser.add_argument('admin_password', type=str, help='Admin password')

    def handle(self, *args, **options):
        print("Loading ontologies")
        launch_import()
        print("Loading genes")
        populate_genes()
        print("Loading pathways")
        process_pathways()
        print("Loading tools")
        populate_default_tools()
        print("Loading data")
        launch_data(options['bson_folder'], options['signature_data_folder'], options['admin_mail'], options['admin_password'])

        print("Setting up indexes")

        for index in registry.get_indices():
            print("Recreating index for " + index._name)
            if index.exists():
                index.delete()
            index.create()
        print("Populate indexes")
        # Populate indexes
        for doc in registry.get_documents():
            print("Populating index for " + doc._index._name)
            qs = doc().get_queryset()
            doc().update(qs)
