# Generated by Django 2.0.13 on 2019-05-24 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('std_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='user')),
                ('status', models.CharField(choices=[('PRIVATE', 'Private'), ('PENDING', 'Pending'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=20)),
                ('description', models.TextField(verbose_name='Description')),
                ('experimental_design', models.TextField(verbose_name='Experimental design')),
                ('study_type', models.CharField(choices=[('INTERVENTIONAL', 'Interventional'), ('OBSERVATIONAL', 'Observational')], default='INTERVENTIONAL', max_length=50)),
                ('results', models.TextField(verbose_name='Results')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_study_created_by', to=settings.AUTH_USER_MODEL)),
                ('subClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_of', to='projects.Project')),
            ],
        ),
    ]
