# Generated by Django 2.0.13 on 2019-07-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20190529_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='subClass',
            new_name='project',
        ),
    ]
