# Generated by Django 2.0.13 on 2019-10-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=50)),
                ('synonyms', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('homolog_id', models.CharField(blank=True, max_length=50)),
                ('ensembl_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
