# Generated by Django 2.0.13 on 2019-12-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0002_auto_20191008_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pathway_id', models.CharField(max_length=50)),
                ('organism', models.CharField(max_length=50)),
                ('genes', models.ManyToManyField(related_name='pathways', to='genes.Gene')),
            ],
        ),
    ]
